"""First model revision

Revision ID: 626b89f87d40
Revises: 7df6c969b8db
Create Date: 2025-03-10 17:30:20.935745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626b89f87d40'
down_revision = '7df6c969b8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Boards'))
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Users'))
    )
    op.create_table('Tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['Boards.id'], name=op.f('fk_Tasks_board_id_Boards')),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_Tasks_user_id_Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Tasks'))
    )
    op.create_table('UserBoards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['Boards.id'], name=op.f('fk_UserBoards_board_id_Boards')),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_UserBoards_user_id_Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserBoards'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserBoards')
    op.drop_table('Tasks')
    op.drop_table('Users')
    op.drop_table('Boards')
    # ### end Alembic commands ###
