"""Fixes Security for passwords

Revision ID: 823ac3709c47
Revises: 626b89f87d40
Create Date: 2025-03-13 10:26:08.777944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823ac3709c47'
down_revision = '626b89f87d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=255), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=25),
               existing_nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_Users_username'), ['username'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_Users_username'), type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
